name: Trigger Auto EMD Release (PDF)

on:
  push:
    tags:
      - 'release/MD*/**'

jobs:
  trigger-pdf-generation:
    uses: embention/sw_CI_Libs/.github/workflows/emd_pdf_asset_release_wf.yml@develop
    with:
      tag_name: ${{ github.ref_name }}
    secrets:
      EMD_API_HOST: ${{ secrets.EMD_API_HOST }}
      JOB_EMD_API_KEY: ${{ secrets.JOB_EMD_API_KEY }}
      ORG_GH_ACTION_ADD_ISSUE_TO_PROJECT: ${{ secrets.ORG_GH_ACTION_ADD_ISSUE_TO_PROJECT }}
