# Improve colors
set -g default-terminal 'screen-256color'

# Some tweaks to the status line
set -g status-bg green
set -g status-right "%H:%M"

# Set scrollback buffer to 1000000
set -g history-limit 1000000

# Mouse support
set -g mouse on