%YAML:1.0
Camera.fx: 320.0
Camera.fy: 320.0
Camera.cx: 320.0
Camera.cy: 240.0

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0
Camera.k4: 0.0

Camera.fps: 15.0

Camera.RGB: 1

Camera.width: 640
Camera.height: 480