"""Typing protocols for curation modules.

These protocols allow static checking without importing concrete FiftyOne
classes at module import time.
"""
from __future__ import annotations

from collections.abc import Iterable
from typing import Any, Protocol


class FiftyOneSampleLike(Protocol):
    id: Any
    filepath: str
    tags: list[str]

    def get_field(self, name: str) -> Any: ...
    def save(self) -> None: ...

    def __getitem__(self, key: str) -> Any: ...


class FiftyOneDatasetLike(Protocol):
    def match_tags(self, tag: str) -> Iterable[FiftyOneSampleLike]: ...
    def load_annotations(self, anno_key: str, **kwargs: Any) -> None: ...
    def save(self) -> None: ...
    def list_annotation_runs(self) -> list[str]: ...
    def get_annotation_info(self, run_key: str) -> Any: ...
    def __iter__(self) -> Iterable[FiftyOneSampleLike]: ...
    def __len__(self) -> int: ...
