import numpy as np

class ORB_coproc:
    @staticmethod
    def get_instance() -> "ORB_coproc": ...
    def get_camera_frame(self) -> np.ndarray: ...
    @staticmethod
    def initialize(width: int, height: int, shs: int, gain: int, camera: bool) -> None: ...

def set_image_path(path: str) -> None: ...
